ws_front:
    resource: "@WSFrontBundle/Controller/"
    type:     annotation
    prefix:   /

ws_menu:
    resource: "@WSMenuBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

note:
    resource: "@NoteBundle/Controller/"
    type:     annotation
    prefix:   /


NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc


admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin


ws_get_tracking_js:
    resource: "@WSCallTrackingBundle/Controller/DefaultController.php"
    type:     annotation
    prefix: /ws

ws_personal:
    resource: "@WSCallTrackingBundle/Controller/PersonalSectionController.php"
    type:     annotation
    prefix: /personal

ws_tools:
    resource: "@WSCallTrackingBundle/Controller/ToolsController.php"
    type:     annotation
    prefix: /ws/tools


