<?php

namespace WS\CallTrackingBundle\Repository;

/**
 * PhoneToUtmToUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhoneToUtmToUserRepository extends \Doctrine\ORM\EntityRepository
{
}
