<?php

namespace WS\CallTrackingBundle\Repository;

/**
 * UserActivityTrackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserActivityTrackRepository extends \Doctrine\ORM\EntityRepository
{
}
