<?php

namespace WS\CallTrackingBundle\Repository;

/**
 * UserActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserActivityRepository extends \Doctrine\ORM\EntityRepository
{
}
