<?php

namespace WS\CallTrackingBundle\Repository;

/**
 * UtmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtmRepository extends \Doctrine\ORM\EntityRepository
{
}
