services:
    ws_zadarnmaclient:
        class: WS\CallTrackingBundle\Service\ZadarmaClient
        arguments: [%zadarma_key%,%zadarma_secret%, 0]
    ws_api_phone_interface:
        class: WS\CallTrackingBundle\Service\ApiPhoneInterface
        arguments: [%zadarma_key%,%zadarma_secret%, 0]